### ISSUE TITLE
API Key created dialog confusing

### ISSUE THREAD

**Issue by ucarion** [ssoready/ssoready#100]
A bit of user feedback from today: the alert dialog after creating an API key is confusing. It should have a button to copy the secret, and the primary should be gated on something like "OK, I copied" instead of immediately going to "View". Otherwise folks click on "View" immediately and then lose the API key secret.

**Comment by Ravindra283** [comment]
Hi @ucarion,
I’m interested in working on this issue. Could you please assign it to me?

**Comment by Ravindra283** [comment]
@ucarion,
are these changes correct?

<img width="1275" alt="Screenshot 2024-08-17 at 09 28 33" src="https://github.com/user-attachments/assets/01017b74-87cc-4eea-a808-2e2ceb87fa50">

**Comment by ucarion** [comment]
@Ravindra283 Yeah that looks good! I was thinking it might be good to make the secret be hidden and have one of those eye icons to reveal it. But I can also just tack that on after your work if you prefer.

**Comment by Ravindra283** [comment]
@ucarion, I can work on that as well if you're okay with it. Do you want these changes included in this ticket, or will you be creating a new one for that
?
