### ISSUE TITLE
Feature Request: Login Hints

### ISSUE THREAD

**Issue by terussell85** [ssoready/ssoready#148]
It would be great if you could support login and domain hints in redirect urls. I primarily care about login (subject) hints but others may care about domain hints.

The parameter is likely different for each SAML provider, so an option to configure it for each SAML connection would probably be ideal.

A few examples:
Okta (LoginHint): https://developer.okta.com/docs/concepts/saml/#understand-sp-initiated-sign-in-flow
Entra (login_hint): https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-saml-protocol#subject

**Comment by Ned-oleary** [comment]
Thanks for the feature request, @terussell85 ! We'll investigate and see when we can get this on the roadmap.

**Comment by ucarion** [comment]
I don't expect we'll be able to prioritize this.

Of the three major IDPs (Okta, Microsoft, Google), none of them support the standard SAML way of doing "hints", i.e. a Subject element in the SAML AuthnRequest. Microsoft opts to do custom, nonstandard things. Okta and Google don't support it at all. Okta-the-IDP (as opposed to their Auth0-like capabilities) only supports this sort of stuff over OIDC, again with nonstandard mechanisms.

The result is that this is going to be a feature that doesn't reliably work, and is going to not have a clean concept that makes IDPs fungible. Plus, it needs to be documented, and will make SSOReady harder to understand. Right now, I'm not seeing a great way to get this to happen.
