### ISSUE TITLE
Feature Request: Friendly Organization Names

### ISSUE THREAD

**Issue by terussell85** [ssoready/ssoready#151]
Small nice-to-have:

Currently the Organizations page just shows Organization ID and External ID. It'd be nice if there was a way to associate a friendly name to the Organization so that it was easier to find the right one in SSOReady without having to go and lookup the id externally.

Not the end of the world, but thought I'd mention it.

**Comment by ucarion** [comment]
This request makes a lot of sense to me! Something like a "Display Name" on organizations is very doable.

**Comment by terussell85** [comment]
Thanks! 🙏
