### ISSUE TITLE
SCIM sync with Entra leads to user being marked as deleted when changing email (userName)

### ISSUE THREAD

**Issue by flore2003** [ssoready/ssoready#164]
We're currently implementing SCIM sync and have noticed users being marked as deleted in SSOReady when you change the user's email address in Entra.

I've looked through the code and it seems in #157 this functionality was introduced. However, the `AuthUpdateSCIMUserEmail` method in `/internal/store/auth_scim.go` seems to always mark the user as deleted.

https://github.com/ssoready/ssoready/blob/8e5c61d53835cd1bd01181db120500be96c2788c/internal/store/auth_scim.go#L313-L315)

Is there a reason why this happens or is this a bug?

**Comment by ucarion** [comment]
Thanks for the report, sorry you ran into this. This was a straightforward oversight in QA.

**Comment by erzaehlsalex** [comment]
Thanks for fixing this so quick.

Now, we have a user in SSOReady that is marked as deleted which should not be the case as only the email should have been changed.

Can you suggest a way to clear the scim users / reprovision the users?

**Comment by ucarion** [comment]
Yeah, sadly with Entra in particular they don't have a way to do a full resync, to my knowledge. So your steps will be to:

1. From the SSOReady side, create a new SCIM directory and bearer token.
2. In Entra, disable user provisioning over SCIM.
3. In Entra, configure user provisioning using the new SCIM directory's SCIM Base URL and bearer token
4. In Entra, reenable user provisioning over SCIM -- now Entra is syncing to the new SCIM directory
5. In SSOReady, mark the new SCIM directory as primary

Sorry this is so complicated. I'm not aware of Entra having drift prevention / "full" resyncing. I wish I had a better answer.
