### ISSUE TITLE
SCIM Sync: Deleted Users in Azure Entra Not Reflected in SSOReady

### ISSUE THREAD

**Issue by RamNow** [ssoready/ssoready#166]
## SCIM User Sync: Deleted Users Not Reflected in SSOReady

We've encountered an issue with SCIM user synchronization between Azure Entra (our identity provider) and SSOReady. When a user is deleted in Azure Entra, this change is not being reflected in SSOReady's SCIM Users list.

### Steps to Reproduce

1. Set up SCIM sync between Azure Entra and SSOReady
2. Delete a user in Azure Entra
3. Check the SCIM Users list in SSOReady

### Expected Behavior

The user should be marked as deleted in the SCIM Users list in SSOReady.

### Actual Behavior

The user account remains in the SSOReady SCIM Users list and is not marked as deleted.

Can you please confirm if this is indeed a bug, and if so, provide any insights on potential fixes or workarounds?

**Comment by ucarion** [comment]
This was resolved as part of #167 -- under the hood, the issue for this user was that Entra was simultaneously PATCHing the user's userName and active state at once. The linked PR makes our support for PATCH considerably more flexible, while preserving the ability to handle Entra-specific logic for their nonstandard request patterns. With that flexibility, we could handle Entra's request, and the user is now up-to-date.
