### ISSUE TITLE
Cloudflare API token required for self-hosted version

### ISSUE THREAD

**Issue by flore2003** [ssoready/ssoready#203]
#191 introduced the `CloudflareAPIKey` config variable as a mandatory config, which leads to the API not starting in our self-hosted environment.

Here is the thrown error message:
```
panic: invalid credentials: API Token must not be empty
```

Our current workaround is setting a dummy value in the API_CLOUDFLARE_API_TOKEN env var, which allows the API to start.

**Comment by ucarion** [comment]
Thanks for the bug report! You'll now be able to use the latest release without having to specify a dummy Cloudflare API key.

**Comment by flore2003** [comment]
Awesome, works! Thanks for the quick fix!
