### ISSUE TITLE
Support deleting SAML connections

### ISSUE THREAD

**Issue by ucarion** [ssoready/ssoready#31]
SAML connections represent a trust relationship between an organization and an outside SAML identity provider. There is not currently a way to delete SAML connections.

This ticket is about adding deletion support for SAML connections.

Some considerations in implementing this:

1. Do we need to specially handle SAML login flows that target a deleted SAML connection? My initial instinct is that there isn't a good reason to do anything fancy in this regard, and to treat it as a normal "404" case.
2. Do we need to specially handle deleting a primary SAML connection? Do we simply leave the organization without a primary SAML connection in such a case?
3. Do we need to support restoring SAML connections? My inclination is that it would be acceptable to not have a sensational answer for "whoops I shouldn't have deleted that" right away, and that we can instead add this later if it turns out there's a common pattern here.
4. Should we support "disabling" SAML connections first? My inclination again is to add this later.

All of this adds up to an initial inclination of implementing by just doing the obvious delete.

**Comment by harshsbhat** [comment]
Hey, I would like to contribute to this repo. Can you guys send me the community link like discord/slack where all the developer, contributors discussions happen?

**Comment by Ned-oleary** [comment]
I made one here: https://join.slack.com/t/ssoready-community/shared_invite/zt-2nyxodco2-k0w3odbKgHG7YBurjZc5tg
