### ISSUE TITLE
Documentation for self-hosting

### ISSUE THREAD

**Issue by Ned-oleary** [ssoready/ssoready#32]
Opening an issue raised by a user seeking documentation on self-hosting SSOReady.

More details to follow.

**Comment by pratikmota** [comment]
+Adding a few personal thoughts for documentation, i thought maybe it will be useful for your discussion.

Many Open-Source projects use `mdBook `for documentation(using `Markdown `files).
Example(Kubernetes): https://book.kubebuilder.io/
Github of mdBook: https://github.com/rust-lang/mdBook

If want in Golang then Hugo is also providing static website creation.
https://gohugo.io/
Hugo Theme: https://themes.gohugo.io/themes/hugo-whisper-theme/

Also, it will be nice if release the documentation version based on the SSOReady release version. So information on docs and software will be aligned with each others version.

**Comment by Ned-oleary** [comment]
Choosing to close this issue given documentation now lives here: https://ssoready.com/docs/self-hosting/self-hosting-sso-ready
