### ISSUE TITLE
Several cosmetic problems on organization detail page

### ISSUE THREAD

**Issue by Ned-oleary** [ssoready/ssoready#36]
Related to #34 and #35

- [ ] Same issues identified in #34 and #35 apply to button and card styling
- [ ] Even though I *do* have to make the screen really small, I can make text overflow on top of other text
- [ ] I think we should re-style the Org ID in the top left. Probably this gets resolved by adding breadcrumbs, but maybe there's an icon we can use

![image](https://github.com/ssoready/ssoready/assets/51148973/83506f8c-4617-4286-9528-2fb1389a263c)
![image](https://github.com/ssoready/ssoready/assets/51148973/25ef7cdb-8d10-4f65-91c8-5ba822d6175e)
![image](https://github.com/ssoready/ssoready/assets/51148973/827cdee0-4b25-4653-a624-52a972f897fa)

**Comment by Ravindra283** [comment]
Hi @Ned-oleary,
I’m interested in working on this issue. Could you please assign this to me?

**Comment by Ned-oleary** [comment]
Yep @Ravindra283, all yours!

**Comment by Ravindra283** [comment]
Hi @Ned-oleary,
Please check the UI changes
https://www.loom.com/share/7076643569a44f45abcc58f1526c7c6b
