### ISSUE TITLE
Several cosmetic problems on SAML Login Flow page

### ISSUE THREAD

**Issue by Ned-oleary** [ssoready/ssoready#38]
Again related to #34, #35, #36

- [ ] App doesn't want to use its space on the right on the SAML Flow card
- [ ] I think we should globally call these "SAML Login Flows" instead of abbreviating to "SAML Flows" 
- [ ] I'd be tempted to come up with a different *null* styling for State and User Attributes. I think User Attributes is in a better place because it has curly braces showing there's nothing there, but I don't think it's always obvious that an empty gray box represents *null* for State. Especially because State tends to confuse people already.

![image](https://github.com/ssoready/ssoready/assets/51148973/f8734631-066f-47e2-9fbe-9862a0212bbe)

**Comment by Ravindra283** [comment]
Hi @Ned-oleary,
I’m interested in working on this issue. Could you please assign this to me?

**Comment by Ravindra283** [comment]
@Ned-oleary,
Which option do you prefer we use for null styling?
![Screenshot 2024-08-19 at 15 25 50](https://github.com/user-attachments/assets/7b2ceee1-dae2-4b6d-807c-0724c1e4104f)
![Screenshot 2024-08-19 at 15 26 15](https://github.com/user-attachments/assets/10526771-9710-4731-817c-4403395913f4)
