### ISSUE TITLE
Responsive design of mutliple pages & changes in tailwind.config.js file for screens 

### ISSUE THREAD

**Issue by Kashyap1ankit** [ssoready/ssoready#50]
The frontend part of the website needs to be improved a lot in case of responsive . Right now the `/environments/new` and multiple same path routes needs improvement . For that , we can update the tailwind.config.js file screens configuration for much precise screens .

It will be great to work if this will assign to me @ucarion 
![Screenshot 2024-06-28 221930](https://github.com/ssoready/ssoready/assets/121277178/38ae0307-6844-4386-8af6-7c890634722e)
![Screenshot 2024-06-28 221944](https://github.com/ssoready/ssoready/assets/121277178/6e97ff25-92df-464e-95f9-4669a8b0f0c3)

**Comment by ucarion** [comment]
Just to make sure I understand you @Kashyap1ankit, are you saying we need new breakpoints to fix the sidebar?

**Comment by ucarion** [comment]
Oh, and thanks for taking the time to help here! ✨ Super appreciated.

**Comment by Kashyap1ankit** [comment]
> Just to make sure I understand you @Kashyap1ankit, are you saying we need new breakpoints to fix the sidebar?

I am saying that tailwind css default `sm` breakpoint starts from `min-width: 640px` so from my experience this screen configuration can be customized so that breakpoints will be more precise . And that can help in making website responsive

You can have a look of my personal project for my breakpoint reference and let me know you opinion @ucarion 

 https://job-preview-dashboard-peach.vercel.app/
