### ISSUE TITLE
Standardize OAuth button sizes

### ISSUE THREAD

**Issue by Ned-oleary** [ssoready/ssoready#77]
Not especially urgent, but we should fix this at some point. We just need the Google / Microsoft buttons to match in the UI.

![image](https://github.com/user-attachments/assets/0f5ee58b-baa6-438c-9304-ba769b13ea28)

**Comment by ShivamChavan01** [comment]
Can i Do it

**Comment by Ned-oleary** [comment]
Yep, all yours! Excited to have you contribute :)

**Comment by Ravindra283** [comment]
@Ned-oleary,
This issue has been resolved and the PR is already merged. Please check and assign the ticket to me.

**Comment by Ned-oleary** [comment]
@Ravindra283 thanks for the nudge. Done.
