### ISSUE TITLE
Improve mobile layout

### ISSUE THREAD

**Issue by Ned-oleary** [ssoready/ssoready#79]
Have become aware that app doesn't work especially well on mobile devices (e.g. iPhone).

Sidebar is probably the biggest problem, although there are others.

This likely involves reworking most of the tailwind classes in the UI with an extra set of breakpoints.

Would basically classify this as (1) not especially important but also (2) something we'll have to do eventually.

**Comment by Ravindra283** [comment]
Hi @Ned-oleary,
I’m interested in working on this issue. Could you please assign this to me?
